api_key: "PSHHtjNi1OV5QqDEodm2EEtvd0DonwJIPF02"
api_secret_key: "ecugts/dcMqRjFrbcYRKWzFm69YefQLee9lNusKrATfyvaQ6eds7o1QMHxFr3eyp0NRipSwFgFd8boG7W4bH5O2SyyB9zm2xNSENg800DYRb1wjT4PK91dTBTBAJ0BZIpgGvVBGcu8kG8ncExZPprRTAHC6mJW11v1oy9yAqFRCZtMWbImE="
stock_account_number: "64474984"
paper_api_key: "PSICb4gadJuCHx4PFfnvPpB8ZjS3aE93oVel"
paper_api_secret_key: "EIhTLd6Li4QD1OFv7eIzf2DaulOrqc3Mjnpa+NtjJAtxcrMu9TYgkxn0gIY7Gzob1HxbfAE5VSIk+MNIYTzJrzRKokZCjVmJRafrGuXU8KKxLf/2w80vIVxS1yWsRZKANOLANiB1sfLnnSuOrM36t/NrI7IfuzZhyhOTaqTtluKXjQG9KeI="
paper_stock_account_number: "50132263"
htsid: "river944"
custtype: "P" # customer type, 개인 "p" 법인 "B"
is_paper_trading: True #모의투자여부


#User Agent
my_agent: "'mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/605.1.15 (khtml, like gecko) version/15.0 safari/605.1.15"

#domain info
url: "https://openapi.koreainvestment.com:9443" #서비스
websocket_url: "ws://ops.koreainvestment.com:21000" #웹소켓
paper_url: "https://openapivts.koreainvestment.com:29443" #모의투자 서비스
paper_websocket_url: "ws://ops.koreainvestment.com:31000"
slack:
  webhook_url: "https://hooks.slack.com/services/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"